// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/api.proto

package proto_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepRequest) Reset() {
	*x = GrepRequest{}
	mi := &file_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepRequest) ProtoMessage() {}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepRequest.ProtoReflect.Descriptor instead.
func (*GrepRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *GrepRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []string               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	MatchCount    int32                  `protobuf:"varint,2,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepResponse) Reset() {
	*x = GrepResponse{}
	mi := &file_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepResponse) ProtoMessage() {}

func (x *GrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepResponse.ProtoReflect.Descriptor instead.
func (*GrepResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *GrepResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *GrepResponse) GetMatchCount() int32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

type GrepAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewText       []string               `protobuf:"bytes,1,rep,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepAddRequest) Reset() {
	*x = GrepAddRequest{}
	mi := &file_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepAddRequest) ProtoMessage() {}

func (x *GrepAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepAddRequest.ProtoReflect.Descriptor instead.
func (*GrepAddRequest) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *GrepAddRequest) GetNewText() []string {
	if x != nil {
		return x.NewText
	}
	return nil
}

type GrepAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepAddResponse) Reset() {
	*x = GrepAddResponse{}
	mi := &file_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepAddResponse) ProtoMessage() {}

func (x *GrepAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepAddResponse.ProtoReflect.Descriptor instead.
func (*GrepAddResponse) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *GrepAddResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_api_api_proto protoreflect.FileDescriptor

const file_api_api_proto_rawDesc = "" +
	"\n" +
	"\rapi/api.proto\x12\x05grepy\"#\n" +
	"\vGrepRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"I\n" +
	"\fGrepResponse\x12\x18\n" +
	"\amatches\x18\x01 \x03(\tR\amatches\x12\x1f\n" +
	"\vmatch_count\x18\x02 \x01(\x05R\n" +
	"matchCount\"+\n" +
	"\x0eGrepAddRequest\x12\x19\n" +
	"\bnew_text\x18\x01 \x03(\tR\anewText\"2\n" +
	"\x0fGrepAddResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode2|\n" +
	"\x0fDistributedGrep\x12/\n" +
	"\x04Grep\x12\x12.grepy.GrepRequest\x1a\x13.grepy.GrepResponse\x128\n" +
	"\aGrepAdd\x12\x15.grepy.GrepAddRequest\x1a\x16.grepy.GrepAddResponseB\x13Z\x11./proto-generatedb\x06proto3"

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData []byte
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)))
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_api_proto_goTypes = []any{
	(*GrepRequest)(nil),     // 0: grepy.GrepRequest
	(*GrepResponse)(nil),    // 1: grepy.GrepResponse
	(*GrepAddRequest)(nil),  // 2: grepy.GrepAddRequest
	(*GrepAddResponse)(nil), // 3: grepy.GrepAddResponse
}
var file_api_api_proto_depIdxs = []int32{
	0, // 0: grepy.DistributedGrep.Grep:input_type -> grepy.GrepRequest
	2, // 1: grepy.DistributedGrep.GrepAdd:input_type -> grepy.GrepAddRequest
	1, // 2: grepy.DistributedGrep.Grep:output_type -> grepy.GrepResponse
	3, // 3: grepy.DistributedGrep.GrepAdd:output_type -> grepy.GrepAddResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_proto_rawDesc), len(file_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
